from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, Field, model_validator

from app.models.enums import (
    AIResponseType,
    ActionType,
    ActorType,
    ApprovalSource,
    ApprovalStatus,
    AutonomyMode,
    AutonomyStatus,
    DecisionState,
    ExecutionMode,
    ExecutionState,
    ImpactClassification,
    ImpactStatus,
    InvestigationStatus,
    MeasurementMode,
    OutcomeStatus,
    SignalSeverity,
    SignalStatus,
    StageType,
)


def utc_now() -> datetime:
    """Returns current UTC timestamp."""
    return datetime.now(timezone.utc)


def generate_id(prefix: str = "obj") -> str:
    """Generates unique prefixed identifier."""
    return f"{prefix}-{uuid.uuid4().hex[:10]}"


class DetectionResult(BaseModel):
    """Standardized deterministic detector output."""
    signal_type: str
    title: str
    description: str
    severity: SignalSeverity
    baseline_value: float
    current_value: float
    change_percentage: float
    decline_percentage: float
    metric_name: str
    evidence: Dict[str, Any] = Field(default_factory=dict)
    detected_at: datetime = Field(default_factory=utc_now)


class Signal(BaseModel):
    """Business signal detected from merchant data streams."""
    signal_id: str = Field(default_factory=lambda: generate_id("sig"))
    merchant_id: str
    signal_type: str
    severity: SignalSeverity = SignalSeverity.MEDIUM
    metric_name: str
    baseline_value: float
    observed_value: float
    variance_percentage: float = 0.0
    change_percentage: float = 0.0
    decline_percentage: float = 0.0
    description: str
    status: SignalStatus = SignalStatus.ACTIVE
    detected_at: datetime = Field(default_factory=utc_now)
    context_data: Dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def sync_percentage_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            change = data.get("change_percentage")
            decline = data.get("decline_percentage")
            variance = data.get("variance_percentage")
            
            if change is not None and variance is None:
                data["variance_percentage"] = float(change)
            elif variance is not None and change is None:
                data["change_percentage"] = float(variance)
            
            if decline is None:
                eff = float(data.get("change_percentage", data.get("variance_percentage", 0.0)))
                data["decline_percentage"] = round(abs(eff), 2) if eff < 0 else 0.0
        return data


class Investigation(BaseModel):
    """Deep investigation finding hypotheses and potential root causes."""
    investigation_id: str = Field(default_factory=lambda: generate_id("inv"))
    signal_id: str
    merchant_id: str
    status: InvestigationStatus = InvestigationStatus.COMPLETED
    hypotheses: List[str] = Field(default_factory=list)
    root_causes: List[str] = Field(default_factory=list)
    supporting_evidence: Dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(ge=0.0, le=1.0, default=0.8)
    summary: str
    investigated_at: datetime = Field(default_factory=utc_now)


class ActionProposal(BaseModel):
    """Proposal generated by LLM or planner based on investigation findings."""
    proposal_id: str = Field(default_factory=lambda: generate_id("prop"))
    action_id: Optional[str] = None
    signal_id: str
    investigation_id: Optional[str] = None
    merchant_id: str
    action_type: ActionType
    objective: Optional[str] = ""
    target_segment: Optional[str] = "repeat_customer, regular"
    target_customer_count: Optional[int] = 0
    incentive_type: Optional[str] = "CASHBACK"
    incentive_value: Optional[float] = 0.0
    duration: Optional[str] = "7 days"
    parameters: Dict[str, Any] = Field(default_factory=dict)
    reason: str
    confidence: float = Field(ge=0.0, le=1.0, default=0.85)
    estimated_cost_inr: float = Field(ge=0.0, default=0.0)
    supporting_evidence_ids: List[str] = Field(default_factory=list)
    constraints: Dict[str, Any] = Field(default_factory=dict)
    projected_impact: Dict[str, Any] = Field(default_factory=dict)
    risk_score: float = Field(ge=0.0, le=1.0, default=0.1)
    status: str = "PROPOSED"
    is_fallback: bool = False
    proposed_at: datetime = Field(default_factory=utc_now)
    created_at: Optional[str] = None

    @model_validator(mode="before")
    @classmethod
    def sync_fields_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            pid = data.get("proposal_id")
            aid = data.get("action_id")
            if aid and not pid:
                data["proposal_id"] = aid
            elif pid and not aid:
                data["action_id"] = pid

            params = data.get("parameters")
            if params is None:
                params = {}
            elif isinstance(params, str):
                try:
                    import json
                    params = json.loads(params)
                except Exception:
                    params = {}

            if "incentive_value" in data and "discount_amount" not in params:
                params["discount_amount"] = data["incentive_value"]
            if "estimated_cost_inr" in data and "budget_inr" not in params:
                params["budget_inr"] = data["estimated_cost_inr"]
            if "target_customer_count" in data and "target_count" not in params:
                params["target_count"] = data["target_customer_count"]
            data["parameters"] = params

            ca = data.get("created_at")
            if isinstance(ca, datetime):
                data["created_at"] = ca.isoformat()
            elif not ca:
                data["created_at"] = datetime.now(timezone.utc).isoformat()
        return data

    @model_validator(mode="after")
    def sync_fields_after(self) -> "ActionProposal":
        if not self.action_id:
            self.action_id = self.proposal_id
        if not self.created_at:
            self.created_at = self.proposed_at.isoformat()
        return self


class GuardrailRuleResult(BaseModel):
    """Result of an individual deterministic guardrail check."""
    rule_name: str
    passed: bool
    threshold: Any
    actual_value: Any
    message: str


class GuardrailCheck(BaseModel):
    """Structured result of an individual deterministic guardrail rule check."""
    check_id: str  # e.g. "G1", "G2", ..., "G10"
    check_type: str  # e.g. "MIN_MARGIN", "DAILY_BUDGET", "MAX_DISCOUNT"
    status: str  # "PASS", "FAIL", "WARN", "MODIFIED"
    rule: str
    actual_value: Any
    threshold_value: Any
    message: str
    severity: str = "INFO"  # "INFO", "WARNING", "CRITICAL"


class GuardrailEvaluation(BaseModel):
    """Deterministic evaluation of an ActionProposal against merchant digital-twin constraints.
    
    SAFETY PRINCIPLES:
    - 100% Deterministic and rule-based.
    - Zero LLM authority.
    - overall_status is strictly PASS, MODIFY, BLOCK, or ESCALATE.
    """
    evaluation_id: str = Field(default_factory=lambda: generate_id("grd"))
    action_id: str
    merchant_id: str = "MID-DEMO-98234"
    overall_status: DecisionState = DecisionState.PASS
    passed: bool = True
    checks: List[GuardrailCheck] = Field(default_factory=list)
    passed_checks: List[str] = Field(default_factory=list)
    failed_checks: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    modifications: Dict[str, Any] = Field(default_factory=dict)
    original_values: Dict[str, Any] = Field(default_factory=dict)
    modified_values: Dict[str, Any] = Field(default_factory=dict)
    notes: str = ""
    evaluated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    is_deterministic: bool = True

    # Compatibility aliases for Phase 1 GuardrailResult
    result_id: Optional[str] = None
    proposal_id: Optional[str] = None
    recommended_state: Optional[DecisionState] = None
    evaluated_rules: List[GuardrailRuleResult] = Field(default_factory=list)
    violations: List[str] = Field(default_factory=list)
    modified_parameters: Optional[Dict[str, Any]] = None

    @model_validator(mode="before")
    @classmethod
    def sync_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            eid = data.get("evaluation_id")
            rid = data.get("result_id")
            if rid and not eid:
                data["evaluation_id"] = rid
            elif eid and not rid:
                data["result_id"] = eid

            aid = data.get("action_id")
            pid = data.get("proposal_id")
            if pid and not aid:
                data["action_id"] = pid
            elif aid and not pid:
                data["proposal_id"] = aid

            st = data.get("overall_status")
            rs = data.get("recommended_state")
            if rs and not st:
                data["overall_status"] = rs
            elif st and not rs:
                data["recommended_state"] = st

            mods = data.get("modifications")
            mp = data.get("modified_parameters")
            if mp and not mods:
                data["modifications"] = mp
            elif mods and not mp:
                data["modified_parameters"] = mods
        return data

    @model_validator(mode="after")
    def sync_aliases_after(self) -> "GuardrailEvaluation":
        if not self.result_id:
            self.result_id = self.evaluation_id
        if not self.proposal_id:
            self.proposal_id = self.action_id
        if not self.recommended_state:
            self.recommended_state = self.overall_status
        if not self.modified_parameters and self.modifications:
            self.modified_parameters = self.modifications
        if not self.evaluated_rules and self.checks:
            self.evaluated_rules = [
                GuardrailRuleResult(
                    rule_name=c.check_type,
                    passed=c.status in ("PASS", "MODIFIED"),
                    threshold=c.threshold_value,
                    actual_value=c.actual_value,
                    message=c.message,
                )
                for c in self.checks
            ]
        if not self.violations and self.failed_checks:
            self.violations = [c.message for c in self.checks if c.status == "FAIL"]
        return self


# Backward-compatible alias for Phase 1 code
GuardrailResult = GuardrailEvaluation


class Decision(BaseModel):
    """Authoritative decision produced by DecisionEngine after Guardrail evaluation.
    
    CRITICAL ARCHITECTURE REQUIREMENT:
    ExecutionEngine only accepts a validated Decision object with is_execution_eligible = True.
    Raw ActionProposals can NEVER directly execute.
    """
    decision_id: str = Field(default_factory=lambda: generate_id("dec"))
    action_id: str = ""
    evaluation_id: str = ""
    merchant_id: str = "MID-DEMO-98234"
    decision_state: DecisionState = DecisionState.PASS
    reason: str = ""
    triggered_rules: List[str] = Field(default_factory=list)
    modifications: Dict[str, Any] = Field(default_factory=dict)
    approval_required: bool = False
    approval_status: ApprovalStatus = ApprovalStatus.PENDING
    decided_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    decided_by: str = "MITRA_DECISION_ENGINE"
    approved_at: Optional[str] = None
    rejected_at: Optional[str] = None
    proposal_hash: str = ""
    evaluation_hash: str = ""
    is_deterministic: bool = True
    approved_action: Optional[Dict[str, Any]] = None
    is_execution_eligible: bool = False
    escalation_reason: Optional[str] = None
    requires_human_review: bool = False

    # Backward-compatible aliases for Phase 1 code
    proposal_id: Optional[str] = None
    state: Optional[DecisionState] = None
    rationale: Optional[str] = None
    guardrail_result_id: Optional[str] = None

    @model_validator(mode="before")
    @classmethod
    def sync_decision_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            did = data.get("decision_id")
            row_id = data.get("id")
            if row_id and not did:
                data["decision_id"] = row_id
            elif did and not row_id:
                data["id"] = did

            # Default is_execution_eligible to True if approved and not explicitly set
            if "is_execution_eligible" not in data:
                st = data.get("decision_state") or data.get("state")
                st_val = st.value if hasattr(st, "value") else str(st)
                ap = data.get("approval_status")
                ap_val = ap.value if hasattr(ap, "value") else str(ap)
                if st_val in ("PASS", "MODIFY") and ap_val == "APPROVED":
                    data["is_execution_eligible"] = True

            pid = data.get("proposal_id")
            aid = data.get("action_id")
            if pid and not aid:
                data["action_id"] = pid
            elif aid and not pid:
                data["proposal_id"] = aid

            grid = data.get("guardrail_result_id")
            eid = data.get("evaluation_id")
            if grid and not eid:
                data["evaluation_id"] = grid
            elif eid and not grid:
                data["guardrail_result_id"] = eid

            st = data.get("state")
            dst = data.get("decision_state")
            if st and not dst:
                data["decision_state"] = st
            elif dst and not st:
                data["state"] = dst

            rat = data.get("rationale")
            rsn = data.get("reason")
            if rat and not rsn:
                data["reason"] = rat
            elif rsn and not rat:
                data["rationale"] = rsn

            da = data.get("decided_at")
            if isinstance(da, datetime):
                data["decided_at"] = da.isoformat()

            import json
            if isinstance(data.get("triggered_rules"), str):
                try:
                    data["triggered_rules"] = json.loads(data["triggered_rules"])
                except Exception:
                    data["triggered_rules"] = []

            if isinstance(data.get("modifications"), str):
                try:
                    data["modifications"] = json.loads(data["modifications"])
                except Exception:
                    data["modifications"] = {}

            if isinstance(data.get("approved_action"), str):
                try:
                    data["approved_action"] = json.loads(data["approved_action"])
                except Exception:
                    data["approved_action"] = {}
        return data

    @model_validator(mode="after")
    def sync_decision_aliases_after(self) -> "Decision":
        if not self.proposal_id:
            self.proposal_id = self.action_id
        if not self.action_id and self.proposal_id:
            self.action_id = self.proposal_id

        if not self.guardrail_result_id:
            self.guardrail_result_id = self.evaluation_id
        if not self.evaluation_id and self.guardrail_result_id:
            self.evaluation_id = self.guardrail_result_id

        if self.state is None:
            self.state = self.decision_state
        elif self.decision_state is None:
            self.decision_state = self.state

        if not self.rationale and self.reason:
            self.rationale = self.reason
        elif not self.reason and self.rationale:
            self.reason = self.rationale

        if self.escalation_reason and not self.requires_human_review:
            self.requires_human_review = True

        # Determine execution eligibility
        if self.state not in (DecisionState.PASS, DecisionState.MODIFY):
            self.is_execution_eligible = False
        elif self.approval_required and self.approval_status != ApprovalStatus.APPROVED:
            self.is_execution_eligible = False

        return self


class ExecutionResult(BaseModel):
    """Outcome of action execution by the ExecutionEngine.
    
    SAFETY PRINCIPLES:
    - execution_mode is strictly SIMULATION.
    - simulated is strictly True.
    - Zero real money movement, zero Paytm production API calls.
    """
    execution_id: str = Field(default_factory=lambda: generate_id("exec"))
    decision_id: str
    action_id: str = Field(default="")
    merchant_id: str = Field(default="MID-DEMO-98234")
    action_type: ActionType = Field(default=ActionType.EVENING_REENGAGEMENT_CAMPAIGN)
    execution_state: ExecutionState = Field(default=ExecutionState.COMPLETED)
    status: str = Field(default="COMPLETED")
    success: bool = True
    execution_mode: ExecutionMode = Field(default=ExecutionMode.SIMULATION)
    simulated: bool = True
    approved_action: Dict[str, Any] = Field(default_factory=dict)
    result: Dict[str, Any] = Field(default_factory=dict)
    output_details: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
    executed_at: datetime = Field(default_factory=utc_now)

    @model_validator(mode="before")
    @classmethod
    def _sync_execution_fields(cls, values: Any) -> Any:
        if isinstance(values, dict):
            # Sync execution_state and status
            if "execution_state" in values and values["execution_state"]:
                val = values["execution_state"]
                state_str = val.value if hasattr(val, "value") else str(val)
                values.setdefault("status", state_str)
            elif "status" in values and values["status"]:
                stat_str = str(values["status"]).upper()
                try:
                    values.setdefault("execution_state", ExecutionState(stat_str))
                except ValueError:
                    values.setdefault("execution_state", ExecutionState.COMPLETED)

            # Sync result and output_details
            if "result" in values and values["result"]:
                values.setdefault("output_details", values["result"])
            elif "output_details" in values and values["output_details"]:
                values.setdefault("result", values["output_details"])

            # Success sync
            if "execution_state" in values:
                st = values["execution_state"]
                st_val = st.value if hasattr(st, "value") else str(st)
                if "success" not in values:
                    values["success"] = (st_val == ExecutionState.COMPLETED.value)
        return values


class Outcome(BaseModel):
    """Post-execution measured business impact and digital-twin outcome monitoring."""
    outcome_id: str = Field(default_factory=lambda: generate_id("out"))
    execution_id: str
    decision_id: Optional[str] = None
    action_id: Optional[str] = None
    merchant_id: Optional[str] = "MID-DEMO-98234"

    # Measurement Windows
    baseline_window: Dict[str, Any] = Field(default_factory=dict)
    measurement_window: Dict[str, Any] = Field(default_factory=dict)

    # Detailed metric dictionaries
    baseline_metrics: Dict[str, Any] = Field(default_factory=dict)
    post_action_metrics: Dict[str, Any] = Field(default_factory=dict)
    metric_changes: Dict[str, Any] = Field(default_factory=dict)

    # Status and Modes
    outcome_status: OutcomeStatus = OutcomeStatus.MEASURED
    status: Optional[str] = None
    simulated: bool = True
    measurement_mode: MeasurementMode = MeasurementMode.SIMULATION
    disclaimer: str = "SIMULATED - PROTOTYPE - NOT REAL PAYTM PERFORMANCE"
    measured_at: datetime = Field(default_factory=utc_now)

    # Compatibility fields with Phase 1
    metric_name: Optional[str] = "evening_orders"
    baseline_value: Optional[float] = 0.0
    observed_value: Optional[float] = 0.0
    delta_percentage: Optional[float] = 0.0
    is_positive: Optional[bool] = True

    @model_validator(mode="before")
    @classmethod
    def sync_outcome_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # ID alias
            oid = data.get("outcome_id")
            rid = data.get("id")
            if rid and not oid:
                data["outcome_id"] = rid
            elif oid and not rid:
                data["id"] = oid

            # Status alias
            ost = data.get("outcome_status")
            st = data.get("status")
            if st and not ost:
                data["outcome_status"] = st
            elif ost and not st:
                data["status"] = ost.value if hasattr(ost, "value") else str(ost)

            # JSON string fields deserialization
            for json_field in ("baseline_window", "measurement_window", "baseline_metrics", "post_action_metrics", "metric_changes"):
                val = data.get(json_field)
                if isinstance(val, str):
                    try:
                        import json
                        data[json_field] = json.loads(val)
                    except Exception:
                        data[json_field] = {}

            # Parse measured_at if string
            mat = data.get("measured_at")
            if isinstance(mat, str):
                try:
                    data["measured_at"] = datetime.fromisoformat(mat)
                except Exception:
                    pass
        return data

    @model_validator(mode="after")
    def sync_outcome_aliases_after(self) -> "Outcome":
        if not self.status:
            self.status = self.outcome_status.value
        # If backward compatibility fields are not populated but metric_changes has entries
        if self.metric_changes:
            primary_key = "evening_orders" if "evening_orders" in self.metric_changes else next(iter(self.metric_changes.keys()), None)
            if primary_key and primary_key in self.metric_changes:
                change_data = self.metric_changes[primary_key]
                if isinstance(change_data, dict):
                    if self.delta_percentage == 0.0 or self.delta_percentage is None:
                        pct = change_data.get("percentage_change")
                        self.delta_percentage = float(pct) if pct is not None else 0.0
                    if self.baseline_value == 0.0 or self.baseline_value is None:
                        self.baseline_value = float(change_data.get("baseline", 0.0) or 0.0)
                    if self.observed_value == 0.0 or self.observed_value is None:
                        self.observed_value = float(change_data.get("post_action", 0.0) or 0.0)
                    if self.is_positive is None:
                        self.is_positive = change_data.get("is_positive", True)
        return self


class AuditEvent(BaseModel):
    """Tamper-evident audit trail record for every workflow stage.
    
    SAFETY PRINCIPLES:
    - Zero secret leakage: credentials, API keys, and auth tokens are stripped.
    - Zero hidden LLM reasoning: records structured system events, not chain-of-thought tokens.
    - SHA-256 hash chaining guarantees tamper-evident provenance.
    """
    event_id: str = Field(default_factory=lambda: generate_id("aud"))
    timestamp: datetime = Field(default_factory=utc_now)
    stage: StageType
    actor: str
    action_description: str
    input_payload: Dict[str, Any] = Field(default_factory=dict)
    output_payload: Dict[str, Any] = Field(default_factory=dict)
    integrity_hash: Optional[str] = None
    
    # Phase 11 Audit Extensions
    event_type: str = "WORKFLOW_STEP"
    correlation_id: Optional[str] = None
    merchant_id: str = "MID-DEMO-98234"
    signal_id: Optional[str] = None
    investigation_id: Optional[str] = None
    action_id: Optional[str] = None
    decision_id: Optional[str] = None
    execution_id: Optional[str] = None
    outcome_id: Optional[str] = None
    impact_id: Optional[str] = None
    previous_hash: str = "GENESIS"
    event_hash: Optional[str] = None
    description: Optional[str] = None
    decision: Optional[str] = None
    reason: Optional[str] = None
    source: Optional[str] = "SYSTEM"
    simulated: bool = True

    @model_validator(mode="before")
    @classmethod
    def sync_audit_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # Sync id and event_id
            eid = data.get("event_id")
            row_id = data.get("id")
            if row_id and not eid:
                data["event_id"] = row_id
            elif eid and not row_id:
                data["id"] = eid

            # Sync description and action_description
            desc = data.get("description")
            act_desc = data.get("action_description")
            if desc and not act_desc:
                data["action_description"] = desc
            elif act_desc and not desc:
                data["description"] = act_desc

            # Sync integrity_hash and event_hash
            ih = data.get("integrity_hash")
            eh = data.get("event_hash")
            if ih and not eh:
                data["event_hash"] = ih
            elif eh and not ih:
                data["integrity_hash"] = eh

            # Parse timestamp if string
            ts = data.get("timestamp")
            if isinstance(ts, str):
                try:
                    data["timestamp"] = datetime.fromisoformat(ts)
                except Exception:
                    pass

            # Parse payloads if string
            for p_field in ("input_payload", "output_payload"):
                val = data.get(p_field)
                if isinstance(val, str):
                    try:
                        data[p_field] = json.loads(val)
                    except Exception:
                        data[p_field] = {}
        return data

    @model_validator(mode="after")
    def sync_audit_aliases_after(self) -> "AuditEvent":
        if not self.description:
            self.description = self.action_description
        if not self.event_hash:
            self.event_hash = self.integrity_hash
        return self


class FactItem(BaseModel):
    """Authoritative factual evidence extracted from database digital twin."""
    id: str
    fact_type: str
    statement: str
    source: str
    metric: Optional[str] = None
    baseline_value: Optional[Any] = None
    observed_value: Optional[Any] = None
    provenance: Optional[str] = None


class HypothesisItem(BaseModel):
    """AI hypothesis generated during investigation; strictly non-factual and non-causal."""
    id: str
    hypothesis: str
    confidence: float = 0.8
    is_causal_claim: bool = False
    caveat: str = "Causality is not established; this is an AI interpretation of observed facts."


class WorkflowAuditVerification(BaseModel):
    """Verification result for cryptographic SHA-256 audit chain."""
    valid: bool
    event_count: int
    verification_mode: str = "SHA-256"
    correlation_id: Optional[str] = None
    error: Optional[str] = None
    verified_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    @property
    def verified(self) -> bool:
        return self.valid

    @property
    def tampered(self) -> bool:
        return not self.valid


class ExplainabilitySummary(BaseModel):
    """Comprehensive, structured, non-causal explanation of why MITRA acted."""
    explanation_id: str = Field(default_factory=lambda: generate_id("exp"))
    correlation_id: str
    merchant_id: str = "MID-DEMO-98234"
    
    # 1. Signal
    signal_summary: Dict[str, Any]
    
    # 2. Evidence
    facts: List[FactItem] = Field(default_factory=list)
    hypotheses: List[HypothesisItem] = Field(default_factory=list)
    evidence_provenance: List[Dict[str, Any]] = Field(default_factory=list)
    
    # 3. Action Proposal
    action_summary: Optional[Dict[str, Any]] = None
    
    # 4. Guardrail Evaluation
    guardrail_summary: Optional[Dict[str, Any]] = None
    
    # 5. Decision & Sign-off
    decision_summary: Optional[Dict[str, Any]] = None

    # Autonomy Policy Evaluation
    autonomy_summary: Optional[Dict[str, Any]] = None
    
    # 6. Execution
    execution_summary: Optional[Dict[str, Any]] = None
    
    # 7. Outcome
    outcome_summary: Optional[Dict[str, Any]] = None
    
    # 8. Business Impact & ROI
    business_impact_summary: Optional[Dict[str, Any]] = None
    
    # 9. Audit Timeline & Verification
    audit_timeline: List[Dict[str, Any]] = Field(default_factory=list)
    audit_verification: Optional[WorkflowAuditVerification] = None
    
    # Meta / Safety
    limitations: List[str] = Field(default_factory=list)
    disclaimer: str = "SIMULATED - PROTOTYPE - DIGITAL TWIN. This explanation describes deterministic prototype behavior in a digital twin sandbox. It is not evidence of real Paytm performance."
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class BusinessImpact(BaseModel):
    """Post-outcome deterministic business impact and ROI analysis.
    
    SAFETY PRINCIPLES:
    - 100% deterministic Python calculation; zero LLM numerical authority.
    - Derived strictly from persisted Phase 9 Outcome and approved executed parameters.
    - Zero real money movement, zero real Paytm APIs, zero production credentials.
    - Explicitly marked as SIMULATED / DIGITAL TWIN.
    """
    impact_id: str = Field(default_factory=lambda: generate_id("imp"))
    outcome_id: str
    execution_id: str
    decision_id: Optional[str] = None
    action_id: Optional[str] = None
    merchant_id: str = "MID-DEMO-98234"

    impact_status: ImpactStatus = ImpactStatus.CALCULATED
    status: Optional[str] = None

    # Revenue metrics
    baseline_revenue: float = 0.0
    post_action_revenue: float = 0.0
    incremental_revenue: float = 0.0

    # Order metrics
    baseline_orders: float = 0.0
    post_action_orders: float = 0.0
    incremental_orders: float = 0.0
    orders_change: float = 0.0

    # Evening orders
    baseline_evening_orders: float = 0.0
    post_action_evening_orders: float = 0.0
    evening_orders_change: float = 0.0

    # Campaign cost (clamped parameter strictly preserved)
    campaign_cost: float = 0.0

    # Profit impact (None if reliable COGS/margin data is unavailable; no fabrication)
    gross_profit_impact: Optional[float] = None

    # Deterministic ROI
    roi: Optional[float] = None
    roi_percentage: Optional[float] = None

    # Order & Rupee efficiency
    cost_per_incremental_order: Optional[float] = None
    revenue_per_campaign_rupee: Optional[float] = None

    # Descriptive classification
    impact_classification: ImpactClassification = ImpactClassification.POSITIVE

    # Prototype simulation flags
    simulated: bool = True
    measurement_mode: MeasurementMode = MeasurementMode.SIMULATION
    disclaimer: str = "SIMULATED - PROTOTYPE - NOT REAL PAYTM PERFORMANCE"
    calculated_at: datetime = Field(default_factory=utc_now)

    @model_validator(mode="before")
    @classmethod
    def sync_impact_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # ID alias
            iid = data.get("impact_id")
            rid = data.get("id")
            if rid and not iid:
                data["impact_id"] = rid
            elif iid and not rid:
                data["id"] = iid

            # Status alias
            ist = data.get("impact_status")
            st = data.get("status")
            if st and not ist:
                data["impact_status"] = st
            elif ist and not st:
                data["status"] = ist.value if hasattr(ist, "value") else str(ist)

            # Cast numeric fields safely
            for num_field in (
                "baseline_revenue", "post_action_revenue", "incremental_revenue",
                "baseline_orders", "post_action_orders", "incremental_orders", "orders_change",
                "baseline_evening_orders", "post_action_evening_orders", "evening_orders_change",
                "campaign_cost", "gross_profit_impact", "roi", "roi_percentage",
                "cost_per_incremental_order", "revenue_per_campaign_rupee"
            ):
                if num_field in data and data[num_field] is not None:
                    try:
                        data[num_field] = float(data[num_field])
                    except (ValueError, TypeError):
                        pass

            # Parse calculated_at if string
            cat = data.get("calculated_at")
            if isinstance(cat, str):
                try:
                    data["calculated_at"] = datetime.fromisoformat(cat)
                except Exception:
                    pass
        return data

    @model_validator(mode="after")
    def sync_impact_aliases_after(self) -> "BusinessImpact":
        if not self.status:
            self.status = self.impact_status.value
        return self


class AutonomyEvaluation(BaseModel):
    """Deterministic evaluation of an ActionProposal/Decision against merchant autonomy policy.
    
    SAFETY PRINCIPLES:
    - Autonomy controls approval flow; autonomy NEVER overrides safety.
    - Zero LLM authority; 100% deterministic rule-based evaluation.
    - If Guardrail is BLOCK, result is strictly BLOCKED under ANY autonomy mode.
    - If Guardrail is ESCALATE, result strictly requires human review.
    - If Guardrail is MODIFY, evaluates and executes ONLY clamped parameters (e.g. ₹100, never ₹150).
    - Prototype digital-twin boundary strictly enforced.
    """
    autonomy_evaluation_id: str = Field(default_factory=lambda: generate_id("aut"))
    correlation_id: str = ""
    merchant_id: str = "MID-DEMO-98234"
    action_id: str
    guardrail_evaluation_id: str
    decision_id: str
    autonomy_mode: AutonomyMode = AutonomyMode.APPROVAL_REQUIRED
    guardrail_status: DecisionState = DecisionState.PASS
    approval_required: bool = True
    auto_approval_allowed: bool = False
    auto_approval_reason: str = ""
    approval_source: ApprovalSource = ApprovalSource.PENDING
    actor_type: ActorType = ActorType.SYSTEM
    blocked: bool = False
    escalated: bool = False
    approved_action: Optional[Dict[str, Any]] = None
    evaluated_risk: float = 0.0
    policy_threshold: float = 0.30
    policy_version: str = "1.0.0"
    passed_checks: List[str] = Field(default_factory=list)
    failed_checks: List[str] = Field(default_factory=list)
    evaluated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    simulation_mode: bool = True

    autonomy_status: AutonomyStatus = AutonomyStatus.APPROVAL_REQUIRED

    # Compatibility aliases
    id: Optional[str] = None
    risk_score: Optional[float] = None
    reason: Optional[str] = None

    @model_validator(mode="before")
    @classmethod
    def sync_autonomy_aliases_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            aid = data.get("autonomy_evaluation_id")
            rid = data.get("id")
            if rid and not aid:
                data["autonomy_evaluation_id"] = rid
            elif aid and not rid:
                data["id"] = aid

            rs = data.get("risk_score")
            er = data.get("evaluated_risk")
            if rs is not None and er is None:
                data["evaluated_risk"] = float(rs)
            elif er is not None and rs is None:
                data["risk_score"] = float(er)

            rsn = data.get("reason")
            aar = data.get("auto_approval_reason")
            if rsn and not aar:
                data["auto_approval_reason"] = rsn
            elif aar and not rsn:
                data["reason"] = rsn

            import json
            for f in ("passed_checks", "failed_checks"):
                if isinstance(data.get(f), str):
                    try:
                        data[f] = json.loads(data[f])
                    except Exception:
                        data[f] = []
            if isinstance(data.get("approved_action"), str):
                try:
                    data["approved_action"] = json.loads(data["approved_action"])
                except Exception:
                    data["approved_action"] = {}
        return data

    @model_validator(mode="after")
    def sync_autonomy_aliases_after(self) -> "AutonomyEvaluation":
        if not self.id:
            self.id = self.autonomy_evaluation_id
        if self.risk_score is None:
            self.risk_score = self.evaluated_risk
        if not self.reason:
            self.reason = self.auto_approval_reason

        # Derive autonomy_status
        if self.blocked:
            self.autonomy_status = AutonomyStatus.BLOCKED
        elif self.escalated:
            self.autonomy_status = AutonomyStatus.ESCALATED
        elif self.approval_source == ApprovalSource.AUTO_APPROVED:
            self.autonomy_status = AutonomyStatus.AUTO_APPROVED
        elif self.approval_source == ApprovalSource.HUMAN_APPROVED:
            self.autonomy_status = AutonomyStatus.HUMAN_APPROVED
        elif self.approval_source == ApprovalSource.REJECTED:
            self.autonomy_status = AutonomyStatus.REJECTED
        else:
            self.autonomy_status = AutonomyStatus.APPROVAL_REQUIRED

        return self


class MerchantAutonomyPolicy(BaseModel):
    """Configurable autonomy policy thresholds for a merchant digital-twin profile."""
    merchant_id: str = "MID-DEMO-98234"
    autonomy_mode: AutonomyMode = AutonomyMode.APPROVAL_REQUIRED
    auto_approval_risk_threshold: float = 0.30
    full_autonomy_risk_threshold: float = 0.50
    auto_approval_max_budget: float = 12000.0
    auto_approval_max_discount: float = 100.0
    require_human_for_modify: bool = False
    require_human_for_escalation: bool = True
    simulated: bool = True
    updated_at: Optional[str] = None


class AIContext(BaseModel):
    """Structured, verified context passed to AI advisory providers.
    
    SAFETY PRINCIPLES:
    - Contains ONLY persisted, deterministically verified facts and state.
    - Zero database credentials or raw SQL access.
    - The AI provider is strictly advisory; it cannot mutate this context or execute actions.
    """
    correlation_id: str
    merchant_id: str = "MID-DEMO-98234"
    signal: Optional[Dict[str, Any]] = None
    verified_facts: List[Dict[str, Any]] = Field(default_factory=list)
    investigation: Optional[Dict[str, Any]] = None
    action_proposal: Optional[Dict[str, Any]] = None
    guardrail_result: Optional[Dict[str, Any]] = None
    autonomy_result: Optional[Dict[str, Any]] = None
    decision: Optional[Dict[str, Any]] = None
    execution: Optional[Dict[str, Any]] = None
    outcome: Optional[Dict[str, Any]] = None
    business_impact: Optional[Dict[str, Any]] = None
    user_query: Optional[str] = None


class AIResponse(BaseModel):
    """Standardized advisory output generated by an AI reasoning provider."""
    response_id: str = Field(default_factory=lambda: generate_id("air"))
    correlation_id: str = ""
    provider: str = ""
    response_type: AIResponseType = AIResponseType.SIGNAL_EXPLANATION
    answer: str = ""
    verified_fact_ids: List[str] = Field(default_factory=list)
    fact_ids: List[str] = Field(default_factory=list)
    hypothesis: Optional[str] = None
    confidence: float = 0.85
    is_cached: bool = False
    disclaimer: str = "AI-generated advisory interpretation. Causality is not established. Simulated digital-twin sandbox."
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    @model_validator(mode="before")
    @classmethod
    def sync_fact_ids_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            vf = data.get("verified_fact_ids")
            fi = data.get("fact_ids")
            if vf and not fi:
                data["fact_ids"] = vf
            elif fi and not vf:
                data["verified_fact_ids"] = fi
        return data

    @model_validator(mode="after")
    def sync_fact_ids_after(self) -> "AIResponse":
        if not self.fact_ids and self.verified_fact_ids:
            self.fact_ids = self.verified_fact_ids
        elif not self.verified_fact_ids and self.fact_ids:
            self.verified_fact_ids = self.fact_ids
        return self



class AIProviderStatus(BaseModel):
    """Status telemetry of active and available AI reasoning providers."""
    active_provider: str
    available_providers: List[str]
    gemini_configured: bool
    huggingface_configured: bool
    fallback_active: bool
    simulation_mode: bool = True
    disclaimer: str = "Advisory AI reasoning layer. Deterministic systems retain sole decision and execution authority."


class AIMerchantQuestionRequest(BaseModel):
    """Payload for merchant Q&A copilot queries."""
    question: str
    merchant_id: str = "MID-DEMO-98234"
    correlation_id: Optional[str] = None


class AIDemoScenarioRequest(BaseModel):
    """Payload for triggering interactive demo workflows."""
    scenario: Optional[str] = None
    scenario_id: Optional[str] = None
    merchant_id: str = "MID-DEMO-98234"

