"""Core Deterministic Guardrail Engine for MITRA.

SAFETY PRINCIPLES:
- 100% Deterministic and rule-based.
- Zero LLM authority: Safety decisions strictly generated by code.
- Hard boundaries enforced against SQLite digital-twin configuration.
- Evaluates Phase 5 ActionProposals to produce structured GuardrailEvaluation.
- Strictly PASS, MODIFY, BLOCK, or ESCALATE.
"""
from datetime import datetime, timezone
import json
from typing import Any, Dict, List, Optional
import uuid

from app.core.config import get_settings
from app.core.logging import logger
from app.database.repository import (
    ActionRepository,
    CampaignRepository,
    CustomerRepository,
    GuardrailRepository,
    MerchantRepository,
)
from app.engines.audit_engine.engine import AuditEngine
from app.engines.guardrail_engine.rules import (
    evaluate_g1_minimum_margin,
    evaluate_g2_daily_budget,
    evaluate_g3_maximum_discount,
    evaluate_g4_campaign_frequency,
    evaluate_g5_audience_boundary,
    evaluate_g6_target_segment,
    evaluate_g7_action_type,
    evaluate_g8_duration_boundary,
    evaluate_g9_autonomy_mode,
    evaluate_g10_proposal_integrity,
)
from app.models.contracts import (
    ActionProposal,
    GuardrailCheck,
    GuardrailEvaluation,
    GuardrailResult,
)
from app.models.enums import DecisionState, StageType

settings = get_settings()


class GuardrailEngine:
    """Deterministic Guardrail Engine.
    
    CORE PRINCIPLE:
    "Deterministic systems calculate truth; the LLM interprets it."
    
    This engine deterministically evaluates proposed actions against hard merchant constraints.
    It can output recommended states:
    - PASS: All constraints satisfied.
    - MODIFY: Minor constraint exceeded; auto-adjust parameters safely to valid thresholds.
    - BLOCK: Severe violation, fraudulent risk, or unsafe proposal.
    - ESCALATE: High impact, critical risk, or requires merchant manual approval.
    """

    def __init__(
        self,
        max_budget_inr: Optional[float] = None,
        max_discount_pct: Optional[float] = None,
        max_risk_score: float = 0.7,
        audit_engine: Optional[AuditEngine] = None,
    ):
        self.max_budget_inr = max_budget_inr
        self.max_discount_pct = (
            max_discount_pct if max_discount_pct is not None else settings.MAX_DISCOUNT_PERCENT
        )
        self.max_risk_score = max_risk_score
        self.audit_engine = audit_engine or AuditEngine()

    def evaluate(
        self,
        proposal: Any,
        merchant_id: Optional[str] = None,
    ) -> GuardrailEvaluation:
        """Evaluates an ActionProposal deterministically without LLM intervention."""
        # 1. Resolve ActionProposal contract
        if isinstance(proposal, str):
            action_row = ActionRepository.get_action_proposal(proposal)
            if not action_row:
                raise ValueError(f"Action proposal '{proposal}' not found in digital twin database.")
            proposal_obj = self._row_to_action_proposal(action_row)
        elif isinstance(proposal, ActionProposal):
            proposal_obj = proposal
        else:
            raise TypeError(f"Invalid proposal input type: {type(proposal)}")

        mid = merchant_id or proposal_obj.merchant_id or "MID-DEMO-98234"
        action_id = proposal_obj.proposal_id

        logger.info(
            "Evaluating proposal %s (type: %s) through deterministic guardrails for merchant %s",
            action_id,
            proposal_obj.action_type.value if hasattr(proposal_obj.action_type, "value") else str(proposal_obj.action_type),
            mid,
        )

        # 2. Record audit: GUARDRAIL_EVALUATION_STARTED
        self.audit_engine.record_event(
            stage=StageType.GUARD,
            actor="DeterministicGuardrailEngine",
            action_description=f"GUARDRAIL_EVALUATION_STARTED: Began 10-point deterministic safety check for {action_id}",
            input_payload={
                "action_id": action_id,
                "merchant_id": mid,
                "action_type": proposal_obj.action_type.value if hasattr(proposal_obj.action_type, "value") else str(proposal_obj.action_type),
                "incentive_value": proposal_obj.incentive_value,
                "target_customer_count": proposal_obj.target_customer_count,
            },
            output_payload={"status": "EVALUATING"},
        )

        # 3. Dynamically load merchant constraints from SQLite
        raw_merchant = MerchantRepository.get_merchant(mid)
        if raw_merchant:
            min_margin = float(raw_merchant.get("minimum_margin", 0.10))
            daily_budget = float(self.max_budget_inr if self.max_budget_inr is not None else raw_merchant.get("daily_budget", 12000.0))
            max_discount = float(raw_merchant.get("max_discount", 100.0))
            max_campaign_freq = int(raw_merchant.get("max_campaign_frequency", 3))
            autonomy_mode = str(raw_merchant.get("autonomy_level") or "APPROVAL_REQUIRED")
        else:
            min_margin = 0.10
            daily_budget = float(self.max_budget_inr if self.max_budget_inr is not None else 12000.0)
            max_discount = 100.0
            max_campaign_freq = 3
            autonomy_mode = "APPROVAL_REQUIRED"

        # 4. Dynamically load customer audience summary from SQLite
        cust_summary = CustomerRepository.get_customers_summary(mid)
        eligible_customers = int(cust_summary.get("target_campaign_customers", 486))

        # 5. Dynamically load campaign frequency from SQLite
        campaigns = CampaignRepository.get_campaigns(mid)
        active_campaigns_count = sum(1 for c in campaigns if str(c.get("status", "")).upper() == "ACTIVE")

        # 6. Execute all 10 deterministic checks
        checks: List[GuardrailCheck] = []
        overall_state = DecisionState.PASS
        modifications: Dict[str, Any] = {}
        original_values: Dict[str, Any] = {}
        modified_values: Dict[str, Any] = {}
        notes_list: List[str] = []

        # Check G1: Minimum Margin
        c1, s1 = evaluate_g1_minimum_margin(proposal_obj, min_margin)
        checks.append(c1)
        if s1 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c1.message)

        # Check G2: Daily Budget
        c2, s2, mod_budget = evaluate_g2_daily_budget(proposal_obj, daily_budget)
        checks.append(c2)
        if s2 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c2.message)
        elif s2 == DecisionState.MODIFY and overall_state != DecisionState.BLOCK:
            overall_state = DecisionState.MODIFY
            if mod_budget is not None:
                original_values["estimated_cost_inr"] = proposal_obj.estimated_cost_inr
                modified_values["estimated_cost_inr"] = mod_budget
                modifications["estimated_cost_inr"] = mod_budget
                notes_list.append(c2.message)

        # Check G3: Maximum Discount
        c3, s3, mod_disc = evaluate_g3_maximum_discount(proposal_obj, max_discount, self.max_discount_pct)
        checks.append(c3)
        if s3 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c3.message)
        elif s3 == DecisionState.MODIFY and overall_state != DecisionState.BLOCK:
            overall_state = DecisionState.MODIFY
            if mod_disc:
                for k, v in mod_disc.items():
                    original_values[k] = proposal_obj.parameters.get(k, proposal_obj.incentive_value)
                    modified_values[k] = v
                    modifications[k] = v
                notes_list.append(c3.message)

        # Check G4: Campaign Frequency
        c4, s4 = evaluate_g4_campaign_frequency(active_campaigns_count, max_campaign_freq)
        checks.append(c4)
        if s4 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c4.message)

        # Check G5: Target Audience Boundary
        c5, s5 = evaluate_g5_audience_boundary(proposal_obj, eligible_customers)
        checks.append(c5)
        if s5 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c5.message)

        # Check G6: Target Segment Validity
        c6, s6 = evaluate_g6_target_segment(proposal_obj)
        checks.append(c6)
        if s6 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c6.message)

        # Check G7: Action Type Validity
        c7, s7 = evaluate_g7_action_type(proposal_obj)
        checks.append(c7)
        if s7 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c7.message)

        # Check G8: Duration Boundary
        c8, s8 = evaluate_g8_duration_boundary(proposal_obj, max_duration_days=30)
        checks.append(c8)
        if s8 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c8.message)

        # Check G9: Autonomy Mode
        c9, s9 = evaluate_g9_autonomy_mode(autonomy_mode)
        checks.append(c9)
        if s9 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c9.message)

        # Check G10: Proposal Integrity
        c10, s10 = evaluate_g10_proposal_integrity(proposal_obj)
        checks.append(c10)
        if s10 == DecisionState.BLOCK:
            overall_state = DecisionState.BLOCK
            notes_list.append(c10.message)

        # 7. Aggregate check summaries
        passed_checks = [c.check_id for c in checks if c.status in ("PASS", "MODIFIED")]
        failed_checks = [c.check_id for c in checks if c.status == "FAIL"]
        warnings = [c.message for c in checks if c.status == "WARN" or c.severity == "WARNING"]
        passed = overall_state in (DecisionState.PASS, DecisionState.MODIFY)
        notes = " | ".join(notes_list) if notes_list else "All deterministic safety checks passed successfully."

        eval_id = f"grd-{uuid.uuid4().hex[:10]}"
        now_iso = datetime.now(timezone.utc).isoformat()

        # 8. Assemble structured GuardrailEvaluation
        evaluation = GuardrailEvaluation(
            evaluation_id=eval_id,
            action_id=action_id,
            merchant_id=mid,
            overall_status=overall_state,
            passed=passed,
            checks=checks,
            passed_checks=passed_checks,
            failed_checks=failed_checks,
            warnings=warnings,
            modifications=modifications,
            original_values=original_values,
            modified_values=modified_values,
            notes=notes,
            evaluated_at=now_iso,
            is_deterministic=True,
            # Backward-compatible fields
            result_id=eval_id,
            proposal_id=action_id,
            recommended_state=overall_state,
            modified_parameters=modifications if modifications else None,
        )

        # 9. Idempotent SQLite persistence via GuardrailRepository
        saved_row = GuardrailRepository.create_or_update_evaluation(
            evaluation_id=evaluation.evaluation_id,
            action_id=evaluation.action_id,
            merchant_id=evaluation.merchant_id,
            overall_status=evaluation.overall_status.value,
            passed=evaluation.passed,
            checks=[c.model_dump() for c in evaluation.checks],
            passed_checks=evaluation.passed_checks,
            failed_checks=evaluation.failed_checks,
            warnings=evaluation.warnings,
            modifications=evaluation.modifications,
            original_values=evaluation.original_values,
            modified_values=evaluation.modified_values,
            notes=evaluation.notes,
            evaluated_at=evaluation.evaluated_at,
            is_deterministic=evaluation.is_deterministic,
        )
        if saved_row and saved_row.get("id"):
            evaluation.evaluation_id = saved_row["id"]
            evaluation.result_id = saved_row["id"]

        # 10. Record audit event
        audit_event_name = (
            "GUARDRAIL_PASSED"
            if overall_state == DecisionState.PASS
            else "GUARDRAIL_MODIFICATION_APPLIED"
            if overall_state == DecisionState.MODIFY
            else "GUARDRAIL_BLOCKED"
        )
        self.audit_engine.record_event(
            stage=StageType.GUARD,
            actor="DeterministicGuardrailEngine",
            action_description=f"{audit_event_name}: Evaluated {action_id} -> {overall_state.value}",
            input_payload={"action_id": action_id, "checks_count": len(checks)},
            output_payload={
                "overall_status": overall_state.value,
                "status": overall_state.value,
                "passed": passed,
                "failed_checks": failed_checks,
                "modifications": modifications,
            },
        )

        logger.info(
            "Completed guardrail evaluation for %s: overall_status=%s (passed=%s)",
            action_id,
            overall_state.value,
            passed,
        )
        return evaluation

    @staticmethod
    def _row_to_action_proposal(row: Dict[str, Any]) -> ActionProposal:
        """Helper to convert database row into an ActionProposal contract."""
        from app.api.actions import _row_to_action_proposal
        return _row_to_action_proposal(row)
